appointment_url = "https://calendly.com"
date_format = "Jan 2, 2006"
day_night = true
description = ""
diagram = false
directions = "Enter Building 1 and take the stairs to Office 200 on Floor 2"
docs_section_pager = true
email = "TBA"
font = ""
font_size = "L"
gravatar = false
highlight = true
highlight_languages = ["r"]
link_authors = true
list_delimiter = ", "
local_business_type = ""
logo = ""
math = false
menu_align_right = false
office_hours = ["Monday 10:00 to 13:00", "Wednesday 09:00 to 10:00"]
org_name = ""
phone = "N/A"
plugins_css = []
plugins_js = []
privacy_pack = false
reading_time = true
section_pager = false
sharing = true
sharing_image = ""
site_type = "Person"
theme = "minimal"
time_format = "3:04 PM"
twitter = ""
[address]
city = "Stanford"
country = "United States"
country_code = "US"
postcode = "94305"
region = "CA"
street = "450 Serra Mall"
[comments]
engine = 0
[comments.commentable]
docs = true
page = true
post = true
project = true
publication = true
talk = true
[comments.disqus]
shortname = ""
show_count = true
[coordinates]
latitude = "37.4275"
longitude = "-122.1697"
[edit_page]
repo_branch = "master"
repo_url = "https://github.com/gcushen/hugo-academic"
[edit_page.editable]
docs = true
page = false
post = false
[map]
api_key = ""
engine = 2
zoom = 15
[marketing]
google_analytics = ""
google_tag_manager = ""
[projects]
post_view = 2
publication_view = 2
talk_view = 2
[publications]
citation_style = "apa"
date_format = "January 2006"
[search]
engine = 1
[search.algolia]
api_key = ""
app_id = ""
index_name = ""
show_logo = false
[[contact_links]]
icon = "twitter"
icon_pack = "fab"
link = "https://twitter.com/zerononcense"
name = "Follow Us for More Content + Updates!"
[[contact_links]]
icon = "skype"
icon_pack = "fab"
link = "skype:echo123?call"
name = "Skype Me"
[[contact_links]]
icon = "keybase"
icon_pack = "fab"
link = "https://keybase.io/"
name = "Chat on Keybase"
[[contact_links]]
icon = "comments"
icon_pack = "fas"
link = "https://forum.hash.fail"
name = "Forums"
