---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: academic-kickstart/content/authors/admin
  label: Admin
  create: all
  match: "**/*"
- type: document
  path: config/_default/menus.toml
  label: Menus.toml
- type: directory
  path: academic-kickstart/config/_default
  label: Default
  create: all
  match: "**/*"
- type: document
  path: config/_default/params.toml
  label: 'Params.toml '
- type: directory
  path: content/home
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: config/_default/content
  label: Pages
  create: all
  match: "*"
upload_dir: config/_default/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
