---
label: Article/Report
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: number
  name: view
  label: view
- type: field_group
  name: header
  label: header
  fields:
  - type: text
    name: caption
    label: caption
  - type: text
    name: image
    label: image
- name: text_field
  type: text
  config:
    required: false
  label: text field
  description: 'Where you write all your content '
